apiVersion: apps/v1
kind: Application
metadata:
  name: techtrends 
  namespace: argocd
spec:
  destination:
    namespace: sandbox
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm
    repoURL: https://github.com/renesasito/techtrends
    targetRevision: HEAD
