namespace:
  name: staging
 
service:
  port: 5111
  targetPort: 3111
  protocol : TCP
  type: ClusterIP

image:
  repository: renesasito/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

ports:
- containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz

readinessProbe:
  httpGet:
    path: /healthz
