namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protcol: TCP
  type: ClusterIP

image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
